const MOCK_PUBS = [
	{
        id: '1',
        name: "Abbey Arms",
        lat: 51.4907,
        lon: 0.121081,
        address: "31 Wilton Road\n\nAbbey Wood\n\nSE2 9RH",
        phone: "(020) 8310 1763",
        features: [],
        photoUrl: "assets/PubPhotos/Abbey_Arms.jpeg",
        ownership: "Independent",
        description: "A traditional public house next to Abbey Wood railway station. Refurbished and redecorated in 2015, again in 2019 when it was taken over by Dirty Liquor and again in 2023 following the exit of Dirty Liquor. There is an upstairs function room along with a large garden to the rear.\n\nWell located for extensive national rail, Elizabeth line and bus transport opportunities.",
        area: "Abbey Wood",
    },
	{
        id: '2',
        name: "Birchwood",
        lat: 51.4978,
        lon: 0.11502,
        address: "Grovebury Road\n\nAbbey Wood\n\nSE2 9BB",
        phone: "(020) 8312 4867",
        features: [],
        photoUrl: "assets/PubPhotos/Birchwood.jpeg",
        ownership: "Independent",
        description: "A 1960s pub situated within a contemporary housing estate. The interior has been redecorated in 2015 with a function room to the rear which is also used as a dinning room for Sunday lunch. Outside there is a paved area with seating and a covered smoking area. Live music on is on Friday and Sunday evenings, a quiz night on Thursdays, chess on Mondays and cribbage on Tuesdays.",
        area: "Abbey Wood",
    },
	{
        id: '3',
        name: "George & Dragon",
        lat: 51.5073,
        lon: -0.27185,
        address: "183 High Street\n\nActon\n\nW3 9DJ",
        phone: "(020) 8992 3712",
        features: [],
        photoUrl: "assets/PubPhotos/George_&_Dragon.jpeg",
        ownership: "Remarkable Pubs",
        description: "At the heart of the historic Acton Town Centre, this welcoming venue has three bars of real character; an atmospheric front bar (now used for seating and live music) leads through to a heritage bar with exposed original features probably from the 17th\n\nCentury, and a cavernous and stylish back room which serves as the bar and the currently unused brewery. The bar features a list of landlords dating back to 1759. The back of the bar is dominated with an impressive array of vast copper and chrome brewing vessels, whilst the large square bar in the centre of the room is adorned by two art nouveau statues. The north wall is covered by a Rousseau style leafy mural.",
        area: "Acton",
    },
	{
        id: '4',
        name: "Red Lion & Pineapple",
        lat: 51.5082,
        lon: -0.27649,
        address: "281 High Street\n\nActon\n\nW3 9BP",
        phone: "(020) 8896 2248",
        features: [],
        photoUrl: "assets/PubPhotos/Red_Lion_&_Pineapple.jpeg",
        ownership: "Wetherspoon",
        description: "A Wetherspoon pub at the top of Acton Hill, formerly owned by Fuller\u2019s. Two pubs here were combined in 1906, hence the unique name. The larger room is home to the circular bar, surrounded by red and black tiles. The windows are large, with etched and stained tops, and the walls are decorated with historical photographs of Acton. The smaller room is mainly used by diners, families.and larger groups. A November 2024 refurbishment saw an additional three handpumps fitted allowing some of the popular beers to be on permanently. Alcohol is served from 9am. Note entry and exit is no longer allowed via the smaller room.",
        area: "Acton",
    },
	{
        id: '5',
        name: "Rocket",
        lat: 51.5087,
        lon: -0.26396,
        address: "11 Churchfield Road\n\nActon\n\nW3 6BD",
        phone: "(020) 8993 6123",
        features: [],
        photoUrl: "https://placekitten.com/400/300",
        ownership: "Independent",
        description: "Divided into two parts, the dining area has beige walls and seating plus a pinewood floor whilst the bar area is much darker with much redness and colourfully furnished. The upstairs function room is used by local groups for film clubs, a book club, life drawing classes as well as comedy nights and other live gigs. Brunch served 10-1. Real ale is often not available.",
        area: "Acton",
    },
	{
        id: '6',
        name: "Shepherds Bush Cricket Club",
        lat: 51.51,
        lon: -0.25261,
        address: "38 Bromyard Avenue\n\nActon\n\nW3 7BP",
        phone: "07734 709458",
        features: [],
        photoUrl: "https://placekitten.com/401/301",
        ownership: "Independent",
        description: "Established in 1882 the club is one of the oldest cricket clubs in London and a founder member of the Middlesex County Cricket League in 1972.\n\nThe pump clips were turned round recently so the beer may only be keg when cricket is not being played.",
        area: "Acton",
    },
	{
        id: '7',
        name: "Station House",
        lat: 51.5087,
        lon: -0.26313,
        address: "Station Buildings, Churchfield Road\n\nActon\n\nW3 6BH",
        phone: "(020) 8992 7110",
        features: [],
        photoUrl: "https://placekitten.com/402/302",
        ownership: "Independent",
        description: "Originally the station booking hall, the upstairs is known as the Red Room and houses the open kitchen and bar and is available between 7pm and 11pm (Noon-9pm on Sundays). It can also be hired for private functions and has a large vaulted roof and arched windows. The pub specialises in Southern Italian tapas & artisan pizzas, although a big burger range is also available. The kitchen is open late till 10.30pm (10pm on Sundays). The outside terrace can become busy, especially when the bar is playing amplified music. The building is locally listed.",
        area: "Acton",
    },
	{
        id: '8',
        name: "West London Trades Union Club",
        lat: 51.5065,
        lon: -0.26567,
        address: "33-35 High Street\n\nActon\n\nW3 6ND",
        phone: "(020) 8992 4557",
        features: [],
        photoUrl: "https://placekitten.com/403/303",
        ownership: "Independent",
        description: "This small and friendly Club \u2013 run as a co-operative \u2013 combines excellent real ale with a busy cultural and social life. Two real ales are served from a variety of small independent breweries - and particularly from the Portobello brewery range. The Acton Community Theatre is upstairs, and regular film shows are also held. The Club is usually closed on Saturdays, but opens on some for special events - see website for dates and details. The local CAMRA branch is an associate member \u2013 show a CAMRA membership card or a copy of the Good Beer Guide to gain access. The Club celebrated its 40th anniversary in 2023, and the building has been part of the co-operative movement for over a century.",
        area: "Acton",
    },
	{
        id: '9',
        name: "Bollo",
        lat: 51.4957,
        lon: -0.270079,
        address: "13 Bollo Lane\n\nActon Green\n\nW4 5LR",
        phone: "(020) 8994 6037",
        features: [],
        photoUrl: "https://placekitten.com/404/304",
        ownership: "Independent",
        description: "Corner pub hidden away behind Chiswick Park station. Built in 1885 as the Railway Tavern, it was renamed the Bollo House in 2000. Spacious, and now best described as a community-centred gastropub with a good ambience. Four ale handpumps.  All-day Sunday roasts. Watch pub website for offers.",
        area: "Acton Green",
    },
	{
        id: '10',
        name: "Duke of Sussex",
        lat: 51.4964,
        lon: -0.2641,
        address: "75 South Parade\n\nActon Green\n\nW4 5LF",
        phone: "(020) 8742 8801",
        features: [],
        photoUrl: "https://placekitten.com/400/300",
        ownership: "Independent",
        description: "The Duke of Sussex is named after one of Queen Victoria's uncles rather than Meghan's husband. It dates from the 1840s and was originally owned by a Suffolk Brewer. By the 1890s it was owned by the Cannon Brewery of Clerkenwell and later by the Lion Brewery, For much of the 20th century it was a Taylor Walker house.\n\nRebuilt in 1898 with a mock Tudor frontage, it has a central island counter with exposed floorboards, alcove seating and etched glass screens. Up to five (but usually three) rotating guest ales are available. mostly from London and the Home Counties. The rear room, the decorative ceiling of which is listed, is dedicated to diners and leads through to a large and welcoming garden with hidden corners.  It is both a local and a gastro-pub. There is generally a pub quiz here on Sunday evenings. Next to the terminus of the 94 bus.",
        area: "Acton Green",
    },
	{
        id: '11',
        name: "Swan",
        lat: 51.498,
        lon: -0.265267,
        address: "1 Evershed Walk, 119 Acton Lane\n\nActon Green\n\nW4 5HH",
        phone: "(020) 8994 8262",
        features: [],
        photoUrl: "https://placekitten.com/401/301",
        description: "Street corner pub dating from 1871, which retains a local drinking character despite the addition of a well-regarded gastropub area into part of the original garden \u2013 still one of the best pub gardens in West London. The ever-present Timothy Taylors Landlord is joined by St Austell Tribute. The pub exterior regularly appeared in a 1980s sitcom, and familiar faces from current TV can often now be seen.\n\nFrom 'Acton's Pubs and Inns (1989) :\n\n\"At the Acton Green end of Acton Lane, the lane takes a sharp right turn and then a left turn round an old field boundary. On the corner of this last turn stands the Swan. Acton Lane is an ancient way and there was a cluster of cottages here in early days. The pub is however first recorded in 1871 when the publican was James Brown who owned the house when it passed to the Phoenix Brewery, Latimer Road. The area around that part of Acton Lane was built up rapidly during that period. The pub passed to the Law Guarantee Trust and in 1909 to Charringtons.\n\nIt survived the rebuilding in the area, was renovated and added to ; although the original house can still be seen. It still retains its original garden and some of the trees.\"\n\nIt is rumoured that the pub survived demolition in the 1970s as part of the building of the Beaconsfield Road Council Estate next door because the then Leader of the Council was a regular there.",
        area: "Acton Green",
    },
	{
        id: '12',
        name: "Claret & Ale",
        lat: 51.38,
        lon: -0.073535,
        address: "5 Bingham Corner, Lower Addiscombe Road\n\nAddiscombe\n\nCR0 7AA",
        phone: "(020) 8656 7452",
        features: [],
        photoUrl: "https://placekitten.com/402/302",
        ownership: "Independent",
        description: "Close to Addiscombe Tram Stop, the Claret & Ale is a small, privately owned friendly free house with a constantly changing selection of cask ales in addition to the popular Palmers IPA. Current and coming beers - often including a second Palmers beer - are indicated on a board on the wall opposite the bar. The TV screens show a variety of sporting events, usually with the sound muted. Occasional events are held to raise money for charity. The pub has often been the local CAMRA Croydon Pub of the Year, and is again for 2024.",
        area: "Addiscombe",
    },
	{
        id: '13',
        name: "Cricketers",
        lat: 51.3813,
        lon: -0.062828,
        address: "47 Shirley Road\n\nAddiscombe\n\nCR0 7ER",
        phone: "(020) 3654 9848",
        features: [],
        photoUrl: "https://placekitten.com/403/303",
        ownership: "Independent",
        description: "Refurbished in 2017, The Cricketers has maintained a clean aspect with new flooring and furniture.  Of the six new handpumps, only two of three are in regular use. This has always been a traditional community pub where all are welcome. Real fires will contribute towards the comfortable, lived-in atmosphere in the winter. Live music will be reinstated when custom demands. There are four TVs in the main bar showing different sports; televised sport has always been a great attraction particularly when Crystal Palace matches are televised. Darts is also played competitively in the pub.",
        area: "Addiscombe",
    },
	{
        id: '14',
        name: "Craft Beer Co.",
        lat: 51.5137,
        lon: -0.0784942,
        address: "29-31 Mitre Street\n\nAldgate\n\nEC3A 5BZ",
        phone: "(020) 7929 5112",
        features: [],
        photoUrl: "https://placekitten.com/404/304",
        description: "Opened in 2015 this has a traditional craft feel. Bare brick walls, mirrors from Bass and Burton breweries, wooden floorboards and traditional high tables with stools. The bar has six cask ales with five guest ales and Kent Pale as a house beer. There are eighteen keg lines and a boxed cider. Pies, scotch eggs and sandwiches are the food offering. The smoking area is on the pavement outside. The toilets and a separate area are downstairs. Music is played. Available for private hire on Saturdays.",
        area: "Aldgate",
    },
	{
        id: '15',
        name: "Hoop & Grapes",
        lat: 51.5143,
        lon: -0.0741806,
        address: "47 Aldgate High Street\n\nAldgate\n\nEC3N 1AL",
        phone: "(020) 7481 4583",
        features: [],
        photoUrl: "https://placekitten.com/400/300",
        ownership: "Independent",
        description: "**Being refurbishmed - expected reopening September 10th** Listed Building dating from the 11th century there has been an Inn on the site since the thirteenth century.The current pub was converted from a wine merchant in 1920. It missed the Great Fire of London by a few yards and is one of only a handful of timbered buildings still left in London. Traditional pub food. The low ceilings and soft lights added to the atmosphere in this Grade II listed pub. Sparklers on all beers.",
        area: "Aldgate",
    },
	{
        id: '16',
        name: "Douglas Fir",
        lat: 51.4147,
        lon: -0.0709134,
        address: "144 Anerley Rd\n\nAnerley\n\nSE20 8DL",
        phone: null,
        features: [],
        photoUrl: "https://placekitten.com/401/301",
        ownership: "Independent",
        description: "This craft beer bar re-opened on 26th April 2025 but currently operates as a pop-up bar until further notice. This previously closed without any prior warning at the end of 2024. The Douglas Fir was originally opened in November 2016 and operated by the Gipsy Hill Brewing Company. In premises formerly occupied by a hairdresser, the appearance is similar to many micropubs but the enterprise is more considered as a bar serving craft  beer. The bar has a popular local following as a community hub and is situated roughly half-way between Crystal Palace and Anerley rail/London Overground stations. The name pays homage to the wood used to build the bar top and drinking shelf, sourced through a creative exchange in return for beer. Inside, a single small compact room has a wooden top bar and assorted seating with tables, benches and a couple of armchairs. The interior d\u00e9cor is in shades of blue grey, complemented by the wooden flooring and dim lighting from modern hanging lights and chandelier. Keg beers are served from taps that are fixed on a former steam pipe from the brewery. Popular with the younger generation, this is very family and dog friendly. The atmosphere is easy going and relaxed. Be prepared to share a table. The bar has up to two handpumps with at least one cask ale available. The main draw for beer drinkers is the array of craft keg lines (up to eight) which contain a changing variety of local beers from Gipsy Hill and Southey breweries. Wine and local spirits are also available along with low/no alcohol beers and cans from the fridge. Outside, there are a couple of table sets on the pavement, which are put out during opening hours. Known to the locals as the \"Doug\". The pub name is unique within Great Britain. Instagram page is @douglasfir_crystalpalace Card payment ONLY, no cash accepted.",
        area: "Anerley",
    },
	{
        id: '17',
        name: "Ashtead Village Club",
        lat: 51.3098,
        lon: -0.298355,
        address: "104 The Street\n\nAshtead\n\nKT21 1AW",
        phone: "(01372) 275764",
        features: [],
        photoUrl: "https://placekitten.com/402/302",
        ownership: "Independent",
        description: "CIU affiliated members only club in the centre of the village. Membership by application, with preference given to local residents.",
        area: "Ashtead",
    },
	{
        id: '18',
        name: "Brewery Inn",
        lat: 51.3094,
        lon: -0.300036,
        address: "15 The Street\n\nAshtead\n\nKT21 2AD",
        phone: "(01372) 282110",
        features: [],
        photoUrl: "https://placekitten.com/403/303",
        ownership: "Independent",
        description: "Large pub, which was the former site of George Sayer's Ashtead Brewery in the 19th century. The cellar still includes the brewing well which extends 100 metres under the road, although the brewery closed in 1910. The large bar area has a raised, music free dining area at the rear. A varied range of food is offered, catering for all dietary requirements and includes daily specials. The outdoor space at the rear, where dogs are welcome, has covered areas and is partially grassed. Taken over by Dorking Brewery in summer 2024.",
        area: "Ashtead",
    },
	{
        id: '19',
        name: "Leg of Mutton & Cauliflower",
        lat: 51.3092,
        lon: -0.29964,
        address: "48 The Street\n\nAshtead\n\nKT21 1AZ",
        phone: "(01372) 273858",
        features: [],
        photoUrl: "https://placekitten.com/404/304",
        ownership: "Independent",
        description: "Former 18th century coaching inn. The pub has recently been redecorated throughout with an eclectic mix of furniture, giving a good ambience. The rooms at the back form a comfortable lounge area. Outside is a patio at the front and a garden to the rear, with a large covered smoking area. Families are welcome until 9:00 in the top bar area. Acoustic bands every fortnight on Saturday evenings. The kitchen closed, but will cater for private functions on request.",
        area: "Ashtead",
    },
	{
        id: '20',
        name: "Woodman",
        lat: 51.3143,
        lon: -0.307998,
        address: "238 Barnett Wood Lane\n\nAshtead\n\nKT21 2DA",
        phone: "(01372) 274524",
        features: [],
        photoUrl: "https://placekitten.com/400/300",
        ownership: "Independent",
        description: "A large pub, overlooking Ashtead Common, which is decorated in typical Ember style with painted walls and dividing partitions to give a homely feel. Several of the partitions include open gas fires as a feature, which make it cosy in winter. For summer, there is a patio at the front and a large fenced garden to the rear. Quizzes are held on Wednesday evenings. A good range of food is served all day. Children allowed until 9pm. Guest beers are from the Ember list.",
        area: "Ashtead",
    }
];

export default MOCK_PUBS;

